// ACTIONS
export const FETCHED_DATA = 'FETCHED_DATA';
export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_FAILED = 'FETCHING_DATA_FAILED';

export const LOADING_START = 'LOADING_START';
export const LOADING_STOP = 'LOADING_STOP';
export const MENU_OPENED = 'MENU_OPENED';
export const MENU_CLOSED = 'MENU_CLOSED';
export const UPDATE_WIDTH = "UPDATE_WIDTH";
export const UPDATE_HEIGHT = "UPDATE_HEIGHT";

// TYPE OF DATA TO FETCH
export const DAILY_COVID_DATA = 'DAILY_COVID_DATA';
export const REGIONAL_COVID_DATA = 'REGIONAL_COVID_DATA';
export const COVID_AMBULANCES = 'COVID_AMBULANCES';
export const SELF_ISOLATION = 'SELF_ISOLATION';

// TYPE OF DAILY DATA
export const BROJ_LICA_NA_RESPIRATORU = 'BROJ_LICA_NA_RESPIRATORU_ZA_DATI_DATUM';
export const BROJ_POZITIVNIH_LICA = 'BROJ_POZITIVNIH_LICA_ZA_DATI_DATUM';
export const BROJ_PREMINULIH_LICA = 'BROJ_PREMINULIH_LICA_ZA_DATI_DATUM';
export const BROJ_PREMINULIH_MUSKARACA = 'BROJ_PREMINULIH_MUŠKARACA_ZA_DATI_DATUM';
export const BROJ_HOSPITALIZOVANIH_LICA = 'BROJ_HOSPITALIZOVANIH_LICA_ZA_DATI_DATUM';
export const BROJ_PREMINULIH_ZENA = 'BROJ_PREMINULIH_ŽENA_ZA_DATI_DATUM';
export const UKUPAN_BR_TESTIRANIH_OD_POCETKA = 'UKUPAN_BROJ_TESTIRANIH_LICA_OD_POČETKA_PANDEMIJE';
export const UKUPAN_BR_POZITIVNIH_OD_POCETKA = 'UKUPAN_BROJ_POZITIVNIH_LICA_OD_POČETKA_PANDEMIJE';
export const UKUPAN_BR_PREMINULIH_OD_POCETKA = 'UKUPAN_BROJ_PREMINULIH_LICA_OD_POČETKA_PANDEMIJE';
export const UKUPAN_BR_IZLECENIH_OD_POCETKA = "UKUPAN_BROJ_IZLEČENIH_LICA_OD_POČETKA_PANDEMIJE";
export const BROJ_TESTIRANIH_LICA = 'BROJ_TESTIRANIH_LICA_ZA_DATI_DATUM';

export const BEZ_PODATAKA = 'bez podataka';

export const BR_PREMINULIH_ZENA_SHORT = 'BROJ_PREMINULIH_ZENA';
export const BR_PREMINULIH_MUSKARACA_SHORT = 'BROJ_PREMINULIH_MUSKARACA';
export const BR_POZITIVNIH_LICA_SHORT = 'BROJ_POZITIVNIH_LICA';
export const BR_PREMINULIH_LICA_SHORT = 'BROJ_PREMINULIH_LICA';
export const BR_TESTIRANIH_LICA_SHORT = 'BROJ_TESTIRANIH_LICA';
export const BR_LICA_NA_RESPIRATORU_SHORT = 'BROJ_LICA_NA_RESPIRATORU';

export const COLOR_SCHEME = [
    "#3182BD",
    "#6BAED6",
    "#9ECAE1",
    "#C6DBEF",
    "#E6550D",
    "#FD8D3C",
    "#FDAE6B",
    "#FDD0A2",
    "#31A354",
    "#74C476",
    "#A1D99B"
];

export const REGION_COLOR_SCHEME = [
    "#C6DBEF",
    "#3182BD"
];

export const IE_TEXT_MAIN = "Internet Explorer ne može prikazati ovu web stranicu";
export const IE_SUB_TEXT = "Za bolje korisiničko iskustvo koristite neki drugi internet pretraživač.";
export const ERROR_404_MAIN = "Greška 404";
export const ERROR_404_SUB = "Izgleda da stranica koju tražite ne postoji.";